# Generated by Django 4.2.5 on 2023-09-25 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TT', '0002_roommessages_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='roomMembers',
        ),
        migrations.AddField(
            model_name='room',
            name='roomMembers',
            field=models.ForeignKey(default=0.0004943153732081067, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
