# Generated by Django 4.2.5 on 2023-09-26 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TT', '0004_remove_room_roomname_remove_roommessages_receiver_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roommessages',
            old_name='message',
            new_name='content',
        ),
    ]
